### ISSUE TITLE
Rabbit Hole Plugin does not take Inpainting into consideration.

### ISSUE THREAD

**Issue by LuckyLuigiX4** [AssassinJN/Rabbit-Hole-UI#1]
I thought inpainting was broken for me, but it turns out that inpainting doesn't work if I use the generate function with this plugin. It ends up generating as if I was just using img2img. Example images below.

Original Image:
![image](https://user-images.githubusercontent.com/76882834/215274852-dd08134e-9a62-4a14-9773-7f6811ff346d.png)

Masked Area:
![image](https://user-images.githubusercontent.com/76882834/215274865-eb556727-860b-462a-9699-3ab2e18759d6.png)

An Image that The Rabbit hole plugin generated:
![image](https://user-images.githubusercontent.com/76882834/215274921-5173dbb5-5e66-4283-ab72-4bfaac40ac6b.png)

Image Generated Via Regular Means (A slightly different mask, it was made later):
![image](https://user-images.githubusercontent.com/76882834/215275000-1c18c000-d90f-4283-b6e1-dca733c4d69e.png)

**Comment by AssassinJN** [comment]
Inpainting should now be supported. Get latest and give it a try.
