### ISSUE TITLE
One wrong click and you will be punished.

### ISSUE THREAD

**Issue by Nocturna22** [AssassinJN/Rabbit-Hole-UI#2]
A very good day to you, sir. I admire your work. However, I have unfortunately noticed a small error that has a serious impact on the usability of this plugin :c

When you click on an image in the Gallery View, the button for Show Gallery View disappears and you are condemned to rot in this pitiful view until you take pity on yourself and click Remove on the current image to cancel it. This has the effect that the Show Gallery View button reappears, but now the images are larger where you had previously pretended to delete them. 

![1](https://user-images.githubusercontent.com/46491831/218899806-ed5b42fe-f882-4ce2-9c9e-000a8a79553e.png)
![2](https://user-images.githubusercontent.com/46491831/218899809-32c10882-0409-4cda-b7ae-bb83f94df3e2.png)

**Comment by AssassinJN** [comment]
So when you click on an image in gallery view, it goes into that task and scrolls to the image you clicked on if you have more than one image in a task. Click on any image in that task view and you'll go back out to the gallery view.
