### ISSUE TITLE
Tooltips are pushed off the page

### ISSUE THREAD

**Issue by ImLunaHey** [AssassinJN/Rabbit-Hole-UI#3]
Without plugin             |  With plugin
:-------------------------:|:-------------------------:
![image](https://github.com/AssassinJN/Rabbit-Hole-UI/assets/105922175/f04a103a-8c20-4f00-a351-01980e68b139)  |  ![image](https://github.com/AssassinJN/Rabbit-Hole-UI/assets/105922175/e655e7ba-5f61-4c4b-89fc-0e6fd9ca566d)

Originally reported: [Via Discord](https://canary.discord.com/channels/1014774730907209781/1138065798305431562/1138065798305431562)

**Comment by AssassinJN** [comment]
Submitted a fix for it.
