### ISSUE TITLE
Suggestion: Add the ability to run the prompt in all available models

### ISSUE THREAD

**Issue by yaronelh** [AssassinJN/Rabbit-Hole-UI#4]
Thanks for creating such an awesome plugin, the thing I was actually searching for is the ability to run the same prompt on multiple models, easy solution just to run on all available models, but even better just to select multiple models the prompt should run on. 

Like the models drop down just in rabbit hole and in rabbit hole the model drop down is a multi select component, Where you select which models you want the prompt to run on and it will go through them one by one.

What do you think?

**Comment by AssassinJN** [comment]
It's a great idea, but I am no longer working on this plugin.
